export const MAKE_REQ = "MAKE_REQ"
export const REQ_GETALL_SUCCESS = "REQ_GETALL_SUCCESS"
export const REQ_GETALL_FAIL = "REQ_GETALL_FAIL"

export const OPEN_POPUP = "OPEN_POPUP"
export const REQ_ADD_SUCCESS = "REQ_ADD_SUCCESS"

export const REQ_GETTASKBYID_SUCCESS = "REQ_GETTASKBYID_SUCCESS"

export const REQ_UPDATE_SUCCESS = "REQ_UPDATE_SUCCESS";
export const REQ_DELETE_SUCCESS = "REQ_DELETE_SUCCESS";


